 CREATE TYPE PortCharacterstic AS OBJECT (

   PORTNAME          VARCHAR2(30),

   PORTVALUE            VARCHAR2(20));
   
   
 
 CREATE TYPE PORTCHARACTERSTIC_TABLE AS TABLE OF PORTCHARACTERSTIC;
  
  CREATE TABLE PORTTABLE (id NUMBER, portChar PORTCHARACTERSTIC_TABLE)

       NESTED TABLE portChar STORE AS portCharTable;